// Phase 4 — Disambiguation control.
// Proves the live disambiguation fallback (disambiguate.ts) doesn't mask a wrong-element click
// as a pass: an ok:true resolution that clicks the WRONG product's button would be a false pass,
// exactly the kind of masking risk negative-control.ts guards against for login preconditions.
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EventEmitter } from 'node:events';
import dotenv from 'dotenv';
import { chromium } from 'playwright';
import { disambiguate, isStrictModeViolation } from './disambiguate.js';
import type { DisambiguationBudget } from './disambiguate.js';
import { runTestCases } from './runner.js';
import type { RunnableTestCase } from './runner.js';
import type { TestCase } from './types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const QA_POC_ROOT = path.join(__dirname, '..', '..');
dotenv.config({ path: path.join(QA_POC_ROOT, '.env') });
const OUTPUT_DIR = path.join(QA_POC_ROOT, 'output');

// Deliberately 3 products with the target in the middle (index 2, not first/last) to catch an
// off-by-one in index-based disambiguation.
const SYNTHETIC_PRODUCTS = ['Sauce Labs Backpack', 'Sauce Labs Bike Light', 'Sauce Labs Bolt T-Shirt'];

function syntheticInventoryHtml(): string {
  const cards = SYNTHETIC_PRODUCTS.map(
    (name, i) => `
      <div class="inventory_item">
        <div><a href="#">${name}</a></div>
        <div>$${(9.99 + i).toFixed(2)}</div>
        <button data-test="add-to-cart-${i}">Add to cart</button>
      </div>`,
  ).join('\n');
  return `<!DOCTYPE html><html><body>${cards}</body></html>`;
}

/** Fast, network-independent check: reproduces Sauce Demo's real per-card structure (plain
 * non-semantic divs, identically-named buttons - see qa-poc/context/saucedemo.md:31-36) and
 * verifies disambiguate() resolves to the button belonging to the RIGHT product, not just any
 * button without error. */
async function runSyntheticCheck(): Promise<boolean> {
  console.log("\n=== Synthetic check: does disambiguate() resolve to the RIGHT product's button? ===");
  const browser = await chromium.launch({ headless: process.env.HEADLESS !== 'false' });
  const page = await browser.newPage();
  await page.setContent(syntheticInventoryHtml());

  const target = SYNTHETIC_PRODUCTS[2];
  const locatorSpec = { strategy: 'role' as const, role: 'button', name: 'Add to cart' };

  let matchCount: number | null = null;
  try {
    await page.getByRole('button', { name: 'Add to cart' }).click({ timeout: 2000 });
  } catch (exc) {
    matchCount = isStrictModeViolation(exc)?.matchCount ?? null;
  }

  if (matchCount === null) {
    console.log('VERDICT: FAIL — synthetic page did not reproduce a strict-mode violation as expected.');
    await browser.close();
    return false;
  }

  const budget: DisambiguationBudget = { used: 0, max: 5 };
  const resolved = await disambiguate({
    page,
    locatorSpec,
    actionLabel: `click add to cart button for ${target}`,
    stepKind: 'click',
    matchCount,
    budget,
  });

  if (!resolved.ok) {
    console.log(`VERDICT: FAIL — disambiguate() returned ok:false (${resolved.reason}).`);
    await browser.close();
    return false;
  }

  const resolvedDataTest = await resolved.locator.getAttribute('data-test').catch(() => null);
  await resolved.locator.click(); // sanity: the resolved single-element locator must actually be clickable
  await browser.close();

  const expectedDataTest = `add-to-cart-${SYNTHETIC_PRODUCTS.indexOf(target)}`;
  console.log(`Resolved via: ${resolved.selectorUsed}`);
  console.log(`Resolved element's data-test: ${resolvedDataTest} (expected: ${expectedDataTest})`);

  if (resolvedDataTest === expectedDataTest) {
    console.log(`VERDICT: PASSED — correct product ("${target}") button was resolved and clicked.`);
    return true;
  }
  console.log(
    `VERDICT: FALSE PASS DETECTED — disambiguate() resolved without error but to the WRONG ` +
      `product's button (expected data-test "${expectedDataTest}", got "${resolvedDataTest}").`,
  );
  return false;
}

/** Live, slower check: runs the real add_to_cart.json (as generated by generate.py, with the
 * Part A prompt fix applied) end-to-end against the live site. Reuses the test case's own
 * downstream assertion (the specific product ending up listed in the cart) as the correctness
 * check - a disambiguated PASS here means the right product was genuinely added, not just that
 * some click succeeded without a Playwright error. */
async function runRealAddToCartCheck(): Promise<boolean | null> {
  console.log('\n=== Live check: real add_to_cart.json end-to-end through the disambiguation fallback ===');
  const file = path.join(OUTPUT_DIR, 'add_to_cart.json');
  if (!existsSync(file)) {
    console.log('SKIPPED — output/add_to_cart.json not found. Run `python generate.py` first to produce it.');
    return null;
  }

  const parsed = JSON.parse(readFileSync(file, 'utf-8')) as TestCase | TestCase[] | { testCases?: TestCase[] };
  const testCases = Array.isArray(parsed)
    ? parsed
    : 'testCases' in parsed && Array.isArray(parsed.testCases)
      ? parsed.testCases
      : [parsed as TestCase];
  const runnable: RunnableTestCase[] = testCases.map((testCase, i) => ({
    id: testCases.length > 1 ? `add_to_cart_${i + 1}` : 'add_to_cart',
    storyType: 'ui',
    testCase,
  }));

  const emitter = new EventEmitter();
  const reports = await runTestCases('disambiguation-control', runnable, emitter, {
    headless: process.env.HEADLESS !== 'false',
  });

  // The masking risk this script exists to catch is specifically a WRONG resolution reported as
  // a PASS - since these test cases' own "then" steps assert specific cart contents, a PASS here
  // already implies the correct product was resolved. A FAIL after disambiguation is NOT itself
  // evidence of a masking problem: it just means something else (e.g. an unrelated, pre-existing
  // gap elsewhere in the test) legitimately broke, which is safe, visible, and not a false pass.
  let anyDisambiguatedPass = false;
  for (const report of reports) {
    const disambiguatedSteps = report.steps.filter((s) => s.disambiguated);
    console.log(`\n"${report.name}": ${report.outcome}, ${disambiguatedSteps.length} step(s) auto-disambiguated`);
    if (disambiguatedSteps.length === 0) {
      console.log(
        'NOTE: no step needed disambiguation here - either the Part A prompt fix alone already ' +
          'avoided the ambiguity, or this test case does not exercise the add-to-cart step. Not a ' +
          'failure of the fallback on its own; see the synthetic check above for a guaranteed exercise.',
      );
      continue;
    }
    if (report.outcome === 'PASS') {
      anyDisambiguatedPass = true;
      console.log(
        "VERDICT: PASSED — disambiguation was used and the test case's own downstream assertion " +
          '(the correct product listed in the cart) still passed - a genuine pass, not masked.',
      );
    } else {
      console.log(
        'NOTE: disambiguation was used but the test case still failed for an unrelated reason ' +
          '(see the log above) - not a masking risk, since nothing was reported as a false pass.',
      );
    }
  }

  if (reports.every((r) => r.steps.every((s) => !s.disambiguated))) return null;
  return anyDisambiguatedPass;
}

async function main() {
  const syntheticOk = await runSyntheticCheck();
  const liveResult = await runRealAddToCartCheck();

  const overallOk = syntheticOk && liveResult !== false;
  console.log(
    `\n=== Summary: synthetic check ${syntheticOk ? 'PASSED' : 'FAILED'}, live check ${
      liveResult === null ? 'SKIPPED/NOT EXERCISED' : liveResult ? 'PASSED' : 'FAILED'
    } ===`,
  );
  process.exit(overallOk ? 0 : 1);
}

main();
